version: "3.8"

services:
  # -------------------
  # HADOOP NAMENODE
  # -------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"   # HDFS UI
      - "9000:9000"   # HDFS port
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - bigdata-net

  # -------------------
  # HADOOP DATANODE
  # -------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - bigdata-net

  # -------------------
  # HADOOP RESOURCEMANAGER
  # -------------------
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000 datanode:9864
    ports:
      - "8088:8088"   # YARN UI
    networks:
      - bigdata-net

  # -------------------
  # HADOOP NODEMANAGER
  # -------------------
  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000 datanode:9864 resourcemanager:8088
    networks:
      - bigdata-net

  # -------------------
  # SPARK MASTER
  # -------------------
  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    restart: always
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8080:8080"   # Spark Master UI
      - "4040:4040"   # Spark Job UI
      - "7077:7077"   # Spark port
    networks:
      - bigdata-net

  # -------------------
  # SPARK WORKER
  # -------------------
  spark-worker:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    restart: always
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081:8081"   # Spark Worker UI
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge

volumes:
  namenode:
  datanode:
